<a href="https://colab.research.google.com/github/AzlinRusnan/STQD-6214-Mathematical-Statistic-with-Computing/blob/main/Introduction_to_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x <- 2^2-3
y <- sqrt(sin(pi/3))
z <- 5*log10(4*exp(1))

In [2]:
3*z/x
x^y+x^z

[1] 15.54532

[1] 2

In [3]:
#Vectors
x <- c(1,2,3)
y <- c(4,5,6)
x*2
z <- c(x,y)
z

[1] 2 4 6

[1] 1 2 3 4 5 6

In [4]:
#selecting elements from a vector
x
#[1] 1 2 3
x[c(2,3,1,4)]
#[1]  2  3  1 NA
x[x>1]
#[1] 2 3
length(x)
#[1] 3

[1] 1 2 3

[1]  2  3  1 NA

[1] 2 3

[1] 3

In [5]:
30:11
seq(1,10, by = 0.5)
seq(1,10, length.out=5)
seq(1,10,5)

[1] 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11

[1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0

[1]  1.00  3.25  5.50  7.75 10.00

[1] 1 6

In [6]:
#repetition
rep(2,6)

rep(y,c(2,3,1))
rep(y,rep(2,3))

vector(0)
vector("numeric",5)


[1] 2 2 2 2 2 2

[1] 4 4 5 5 5 6

[1] 4 4 5 5 6 6

ERROR: ignored

In [7]:
#Exercise
x <- seq(2,10,length.out=30)
x
sum(x)
x[15]
x[x>5]
length(x[x>5])

[1]  2.000000  2.275862  2.551724  2.827586  3.103448  3.379310  3.655172
 [8]  3.931034  4.206897  4.482759  4.758621  5.034483  5.310345  5.586207
[15]  5.862069  6.137931  6.413793  6.689655  6.965517  7.241379  7.517241
[22]  7.793103  8.068966  8.344828  8.620690  8.896552  9.172414  9.448276
[29]  9.724138 10.000000

[1] 180

[1] 5.862069

[1]  5.034483  5.310345  5.586207  5.862069  6.137931  6.413793  6.689655
 [8]  6.965517  7.241379  7.517241  7.793103  8.068966  8.344828  8.620690
[15]  8.896552  9.172414  9.448276  9.724138 10.000000

[1] 19

In [8]:
#1. Evaluate the following expressions.
#a) 12.3 + 232.2
12.3 + 232.2

#b) log(𝑒2 + 3)
log(exp(2)+3)

#c) sin(𝜋/4+ 3)
sin(pi/4+3)

#d) tan−1(1.3^2)
atan(1.3^2)

[1] 244.5

[1] 2.340753

[1] -0.6002435

[1] 1.03649

In [9]:
#2. Let 𝑥 = 2.3 and 𝑦 = 3.1. Evaluate the following expressions.
#a) √𝑥4 − 5y
x <- 2.3
y <- 3.1
sqrt(x^4-5*y)

#b)𝑒^𝑥 − 3𝑥 + 𝑦𝑥
exp(x) - 3*x + y^x

#c) cos−1(𝑥/𝑦)
acos(x/y)

#d) log(𝑧 +3𝑧) where 𝑧 = 𝑥2 − log(10𝑦)
z <- x^2-log(10*y)
log(z+3/z)

[1] 3.533285

[1] 16.56791

[1] 0.7348438

[1] 1.244841

In [10]:
#3. Let 𝑥 = 2.3 and 𝑦 = 3.1. Determine whether the following expressions are true or false
x <- 2.3
y <- 3.1
#a) 3𝑥 > 2𝑦
3*x > 2*y
#TRUE

#b) 𝑥^𝑦 ≤ 𝑦^𝑥 AND 3^𝑥 > 𝑦^2.2
(x^y <= y^x) & (3^x > y^2.2)
# TRUE

#c) cos(𝑥) = 0 OR sin(𝑦) > 0
(cos(x) == 0) | (sin(y) > 0)
# TRUE

[1] TRUE

[1] TRUE

[1] TRUE

In [11]:
#4. Let 𝒙 and 𝒚 be vectors where 𝒙 = (6,4,3,20) and 𝒚 = (12,46,2,1). Evaluate the following expressions.
#a) 𝒙 + 2𝒚
x <- c(6,4,3,20)
y <- c(12,46,2,1)
x + 2*y
#[1] 30 96  7 22

#b) ∑ 𝑥𝑖𝑦𝑖
sum(x*y)

#c)max(𝒛) where the 𝑖th component of 𝑧𝑖 = 𝑥𝑖 2 − 10𝑦𝑖. Which component gives this maximum value of 𝒛?
z <- x^2 - 10*y
max(z)
which.max(z)

#d) How would you code to get the components of 𝒚 that is bigger than 10?
y[y>10]

#e) Run this following code: c(x, y). What do you think happen here?
c(x,y)

#f) Run this following code: sum(x[x>5]). What do you think happen here?
sum(x[x>5])

#g) Run this following code: sum(x>5). What do you think happen here?
sum(x>5)


[1] 30 96  7 22

[1] 282

[1] 390

[1] 4

[1] 12 46

[1]  6  4  3 20 12 46  2  1

[1] 26

[1] 2

In [12]:
#5. Without using only the c() function, create the following:
#a) A vector containing integers from -10 to 10.
-10:10

#b) A sequence of numbers from 0 to 100 where the length of sequence is 1000.
seq(0,100,length.out =1000)

#c) A vector of 0’s with length 10.
rep(0,10)
vector("numeric", 10)

#d) The vector (“A”, “B”, “C”, “A”, “B”, “C”, “A”, “B”, “C”).
rep(c("A","B","C"),3)

#e) The vector (“A”, “A”, “A”, “B”, “B”, “B”, “C”, “C”, “C”).
rep(c("A","B","C"),each = 3)

rep(c("A","B","C"),rep(3,3))

[1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7   8
[20]   9  10

[1]   0.0000000   0.1001001   0.2002002   0.3003003   0.4004004   0.5005005
   [7]   0.6006006   0.7007007   0.8008008   0.9009009   1.0010010   1.1011011
  [13]   1.2012012   1.3013013   1.4014014   1.5015015   1.6016016   1.7017017
  [19]   1.8018018   1.9019019   2.0020020   2.1021021   2.2022022   2.3023023
  [25]   2.4024024   2.5025025   2.6026026   2.7027027   2.8028028   2.9029029
  [31]   3.0030030   3.1031031   3.2032032   3.3033033   3.4034034   3.5035035
  [37]   3.6036036   3.7037037   3.8038038   3.9039039   4.0040040   4.1041041
  [43]   4.2042042   4.3043043   4.4044044   4.5045045   4.6046046   4.7047047
  [49]   4.8048048   4.9049049   5.0050050   5.1051051   5.2052052   5.3053053
  [55]   5.4054054   5.5055055   5.6056056   5.7057057   5.8058058   5.9059059
  [61]   6.0060060   6.1061061   6.2062062   6.3063063   6.4064064   6.5065065
  [67]   6.6066066   6.7067067   6.8068068   6.9069069   7.0070070   7.1071071
  [73]   7.2072072   7.3073073   7.4074074   7.5075075   7.6076076   7.7077077
  [79]   7.8078078   7.9079079   8.0080080   8.1081081   8.2082082   8.3083083
  [85]   8.4084084   8.5085085   8.6086086   8.7087087   8.8088088   8.9089089
  [91]   9.0090090   9.1091091   9.2092092   9.3093093   9.4094094   9.5095095
  [97]   9.6096096   9.7097097   9.8098098   9.9099099  10.0100100  10.1101101
 [103]  10.2102102  10.3103103  10.4104104  10.5105105  10.6106106  10.7107107
 [109]  10.8108108  10.9109109  11.0110110  11.1111111  11.2112112  11.3113113
 [115]  11.4114114  11.5115115  11.6116116  11.7117117  11.8118118  11.9119119
 [121]  12.0120120  12.1121121  12.2122122  12.3123123  12.4124124  12.5125125
 [127]  12.6126126  12.7127127  12.8128128  12.9129129  13.0130130  13.1131131
 [133]  13.2132132  13.3133133  13.4134134  13.5135135  13.6136136  13.7137137
 [139]  13.8138138  13.9139139  14.0140140  14.1141141  14.2142142  14.3143143
 [145]  14.4144144  14.5145145  14.6146146  14.7147147  14.8148148  14.9149149
 [151]  15.0150150  15.1151151  15.2152152  15.3153153  15.4154154  15.5155155
 [157]  15.6156156  15.7157157  15.8158158  15.9159159  16.0160160  16.1161161
 [163]  16.2162162  16.3163163  16.4164164  16.5165165  16.6166166  16.7167167
 [169]  16.8168168  16.9169169  17.0170170  17.1171171  17.2172172  17.3173173
 [175]  17.4174174  17.5175175  17.6176176  17.7177177  17.8178178  17.9179179
 [181]  18.0180180  18.1181181  18.2182182  18.3183183  18.4184184  18.5185185
 [187]  18.6186186  18.7187187  18.8188188  18.9189189  19.0190190  19.1191191
 [193]  19.2192192  19.3193193  19.4194194  19.5195195  19.6196196  19.7197197
 [199]  19.8198198  19.9199199  20.0200200  20.1201201  20.2202202  20.3203203
 [205]  20.4204204  20.5205205  20.6206206  20.7207207  20.8208208  20.9209209
 [211]  21.0210210  21.1211211  21.2212212  21.3213213  21.4214214  21.5215215
 [217]  21.6216216  21.7217217  21.8218218  21.9219219  22.0220220  22.1221221
 [223]  22.2222222  22.3223223  22.4224224  22.5225225  22.6226226  22.7227227
 [229]  22.8228228  22.9229229  23.0230230  23.1231231  23.2232232  23.3233233
 [235]  23.4234234  23.5235235  23.6236236  23.7237237  23.8238238  23.9239239
 [241]  24.0240240  24.1241241  24.2242242  24.3243243  24.4244244  24.5245245
 [247]  24.6246246  24.7247247  24.8248248  24.9249249  25.0250250  25.1251251
 [253]  25.2252252  25.3253253  25.4254254  25.5255255  25.6256256  25.7257257
 [259]  25.8258258  25.9259259  26.0260260  26.1261261  26.2262262  26.3263263
 [265]  26.4264264  26.5265265  26.6266266  26.7267267  26.8268268  26.9269269
 [271]  27.0270270  27.1271271  27.2272272  27.3273273  27.4274274  27.5275275
 [277]  27.6276276  27.7277277  27.8278278  27.9279279  28.0280280  28.1281281
 [283]  28.2282282  28.3283283  28.4284284  28.5285285  28.6286286  28.7287287
 [289]  28.8288288  28.9289289  29.0290290  29.1291291  29.2292292  29.3293293
 [295]  29.4294294  29.5295295  29.6296296  29.7297297  29.8298298  29.9299299
 [301]  30.0300300  30.1301301  30.2302302  30.330330

[1] 0 0 0 0 0 0 0 0 0 0

[1] 0 0 0 0 0 0 0 0 0 0

[1] "A" "B" "C" "A" "B" "C" "A" "B" "C"

[1] "A" "A" "A" "B" "B" "B" "C" "C" "C"

[1] "A" "A" "A" "B" "B" "B" "C" "C" "C"

In [13]:
#Matrices
#matrix()

x <- c(5,4,3,6,1,7)
X <- matrix(x,ncol=2,nrow = 3, byrow=T)
matrix(x,ncol=2,nrow = 3)
#by default dia akan fill up column

X[3,2]
X[,2]
X[3,]

X[c(1,3,2),2]
X[c(1,3,2),]
X[c(1,3),]

#Matrix Operations
X*3

x1 <- c(5,4,3)
x2 <- c(6,1,7)
cbind(x1,x2)
rbind(x1,x2)

[,1] [,2]
[1,] 5    6   
[2,] 4    1   
[3,] 3    7

[1] 7

[1] 4 6 7

[1] 1 7

[1] 4 7 6

[,1] [,2]
[1,] 5    4   
[2,] 1    7   
[3,] 3    6

[,1] [,2]
[1,] 5    4   
[2,] 1    7

[,1] [,2]
[1,] 15   12  
[2,]  9   18  
[3,]  3   21

x1 x2
[1,] 5  6 
[2,] 4  1 
[3,] 3  7

[,1] [,2] [,3]
x1 5    4    3   
x2 6    1    7

In [14]:
#modify an element of a vector/matrix

x <- c(1,10,5,4,1,1)
X <- matrix(x,ncol = 3)
X
X[2,1]
X[,2]

y <- c(3,5,15,2)
Y <- matrix(y,nrow=2)
solve(Y)
t(X)%*%Y


[,1] [,2] [,3]
[1,]  1   5    1   
[2,] 10   4    1

[1] 10

[1] 5 4

[,1]        [,2]       
[1,] -0.02898551  0.21739130
[2,]  0.07246377 -0.04347826

[,1] [,2]
[1,] 53   35  
[2,] 35   83  
[3,]  8   17

In [15]:
a <- c(21,2,3,14)
A <- matrix(a, nrow=2)
A
#Dr Atiqah
#a1<- c(21,2)
#a2<- c(3,14)
#A<-cbind(a1,a2)
b <- c(12, 45, 5 ,1)
B <- matrix(b, nrow=2)
B


[,1] [,2]
[1,] 21    3  
[2,]  2   14

[,1] [,2]
[1,] 12   5   
[2,] 45   1

In [16]:
#b) Evaluate 𝐴 + 𝐵.
A+B
#c) Evaluate 𝐴𝐵.
A%*%B
#d) Evaluate 𝐴−1
solve(A)
#e) Evaluate (𝐴𝑇𝐵)−1
solve(t(A) %*% B)

[,1] [,2]
[1,] 33    8  
[2,] 47   15

[,1] [,2]
[1,] 387  108 
[2,] 654   24

[,1]         [,2]       
[1,]  0.048611111 -0.01041667
[2,] -0.006944444  0.07291667

[,1]          [,2]        
[1,] -0.0004727439  0.001744262
[2,]  0.0108568075 -0.005575117

In [17]:
D <- matrix(c(3,52,7,2,10,1), ncol= 3,nrow=2, byrow=TRUE)
D
x <- matrix(c(75,2), nrow=2)
x
E <- cbind(D,x)
E
F <- D[,c(1,2)]
F
#F <- D[,1:2]
#D[,-3]
#D[,c(1,-3)]
> myscan <- scan()
1: 5
2: 6
3: 7
4: 8
5: 9
6: 4
7: 6
8: 3
9: 1
10: 2
11:
Read 10 items
> myscan
 [1] 5 6 7 8 9 4 6 3 1 2
> myscan <- scan(what="")
1: Ali
2: Ahmad
3: Abu
4:
Read 3 items
>
> myscan
[1] "Ali"   "Ahmad" "Abu"
> matrix(scan(), ncol=3, byrow=T)
1: 12 32 54
4: 45
5: 62
6: 91
7:
Read 6 items
     [,1] [,2] [,3]
[1,]   12   32   54
[2,]   45   62   91

ERROR: ignored